### ISSUE TITLE
Avoid download dataset programmatically.  

### ISSUE THREAD

**Issue by t-k-** [borgwang/tinynn#1]
The MNIST example is like torchvision, it download the dataset programmatically when the data file is not in specific directory. I personally had very bad experience using torchvision because it does not use CDN link and no progress bar is given, in China, it is painfully slow. Moreover, it hard-code the link in the code and add maintenance cost. I think tinynn is doing the same thing.

I imagine if I want to contribute another example, according to the convention, I will need to import urllib and write `try except` and `mkdir` logic in my code just to help user download the dataset. Why not make it old-fashion and simpler to provide list of download links in text to make user and contributor life easier?

I love the cleanness of tinynn, I think I can learn a lot from this code. But I suggest to keep the example code small and instead provide documentation or text description to ask the user to download dataset themselves with a list of links (official link, Baidu Yun, etc.).

**Comment by borgwang** [comment]
@t-k- I prefer getting datasets ready and people can just run one command to get a quick start without extra work. Also maintaining one link is simpler compare to a list of links.

**Comment by t-k-** [comment]
@borgwang Thanks for your reply. Nevertheless, I think having a progress bar is at least useful, so I have made a pull request #3. Feel free to let me know whether you like it, if you accept, I will go ahead and change the binary_classification example accordingly.

**Comment by t-k-** [comment]
Also, my point to have a list of URLs is to exactly help people get a quick start without extra work. Otherwise people like me in China would easily lost patience when downloading the default MNIST link.
