### ISSUE TITLE
SOFTPLUS

### ISSUE THREAD

**Issue by Zhangang1999** [borgwang/tinynn#25]
should SOFTPLUS be Softplus(x)= log(1+exp(x))  ？ The code looks like Softplux(x) = log(1+exp(-x)) + max（x,0.0）.I tried to compute them.And they are equivalent. But why should we use this more complex way?

**Comment by borgwang** [comment]
@Zhangang1999  When `x` is a large positive number, `exp(x)` might be overflow. The implementation here is for numerical stability.
