### ISSUE TITLE
可以添加transformer ，seq2seq 和 attention 这些吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [borgwang/tinynn#29]
是从知乎上看到的，非常喜欢也这个工程，觉得这个工程对初学者太友好了，比直接使用大深度学习框架，能了解更多的细节。

看了一些transformer 的资料，还是不太理解它是怎么实现的，在网上找的transformer 实现都是基于pytorch 和 tf实现的，没有像这样从头开始实现的。

**Comment by t-k-** [comment]
可以参考这个实现：https://github.com/t-k-/pytorchic-bert

**Comment by borgwang** [comment]
@zuowanbushiwo 很高兴对你有帮助，由于个人原因暂时没有支持 transformer/attention 相关模型的计划，等有空余时间了肯定会看看。如果你已经在 tinynn 上实现了相关的模块，也欢迎提交 MR~
