### ISSUE TITLE
One suggestion on file header

### ISSUE THREAD

**Issue by t-k-** [borgwang/tinynn#5]
I think it is a very outdated practice to add information such as author, date and filename into file header. These are tracked by git already (in much better way), and they only add maintenance cost. Just a suggestion, for later new files to be created.

I come across this suggestion because it makes me hesitate whether I should modify your header when I change a minor thing in the code. And it will also cause confusion for potential contributors of this project (if you want more people to participate).

If you agree, I can help to remove those fields in current source code.

**Comment by t-k-** [comment]
BTW. Your project description has a typo. Now it is "A lightweight deep learning libaray". Should be `library`.

**Comment by borgwang** [comment]
@t-k- Typo fixed. Thanks for the advice. I will re-format the file header soon.

**Comment by t-k-** [comment]
You are welcome.
